# Generated by Django 5.2.8 on 2025-11-11 22:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID from the upstream source', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='job',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('80000hours', '80,000 Hours'), ('idealist', 'Idealist')], default='manual', max_length=50),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the organization'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['source', 'external_id'], name='jobs_job_source_d66f4d_idx'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('source', 'external_id'), name='unique_job_source_external_id'),
        ),
        migrations.AlterField(
            model_name='job',
            name='posted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
