# Generated by Django 5.2.8 on 2025-11-11 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_external_id_job_raw_data_job_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('80000hours', '80,000 Hours'), ('idealist', 'Idealist'), ('reliefweb', 'ReliefWeb')], default='manual', max_length=50),
        ),
    ]
