# Generated by Django 5.2.8 on 2025-11-30 21:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurposeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose_statement', models.TextField(blank=True, help_text='LLM-generated based on resonances')),
                ('top_causes', models.JSONField(default=list, help_text='List of {category, count} dicts')),
                ('resonated_skills', models.JSONField(default=list, help_text='Skills from resonated stories')),
                ('category_scores', models.JSONField(default=dict, help_text='Category slug → score mapping')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purpose_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('instructions', models.TextField(help_text='Step-by-step instructions')),
                ('task_type', models.CharField(choices=[('data_entry', 'Data Entry'), ('tagging', 'Tagging/Labeling'), ('research', 'Research'), ('translation', 'Translation'), ('review', 'Review/Feedback'), ('other', 'Other')], max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('time_estimate_minutes', models.PositiveIntegerField(default=15, help_text='Estimated time in minutes')),
                ('task_url', models.URLField(blank=True, help_text='External URL where task is completed')),
                ('impact_statement', models.TextField(help_text='Why this matters (shown to users)')),
                ('auto_verify', models.BooleanField(default=False, help_text='Automatically verify completions')),
                ('is_active', models.BooleanField(default=True)),
                ('completion_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(related_name='sprints', to='jobs.category')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='jobs.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=200)),
                ('author_title', models.CharField(max_length=200)),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='stories/authors/')),
                ('is_verified', models.BooleanField(default=False, help_text='Verified by organization')),
                ('content_raw', models.TextField(help_text='Raw story text before formatting')),
                ('content', models.TextField(help_text='Formatted story (2-3 sentences, outcome-focused)')),
                ('skills', models.JSONField(blank=True, default=list, help_text='List of skill tags')),
                ('resonate_count', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(related_name='stories', to='jobs.category')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='jobs.organization')),
                ('related_jobs', models.ManyToManyField(blank=True, related_name='stories', to='jobs.job')),
            ],
            options={
                'verbose_name_plural': 'Stories',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryResonance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('resonance_type', models.CharField(choices=[('cause', 'The cause/mission'), ('work', 'The type of work'), ('outcome', 'The outcome/impact'), ('org', 'The organization')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resonances', to='jobs.story')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('resonated_stories', models.JSONField(default=list, help_text='List of story UUIDs')),
                ('category_interactions', models.JSONField(default=dict, help_text='Category slug → interaction count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('converted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SprintCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Started'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='started', max_length=20)),
                ('submission_notes', models.TextField(blank=True)),
                ('submission_url', models.URLField(blank=True)),
                ('impact_card_text', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='jobs.sprint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'unique_together': {('sprint', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['status', '-published_at'], name='jobs_story_status_6df1d5_idx'),
        ),
        migrations.AddIndex(
            model_name='storyresonance',
            index=models.Index(fields=['session_key', 'story'], name='jobs_storyr_session_2de867_idx'),
        ),
        migrations.AddIndex(
            model_name='storyresonance',
            index=models.Index(fields=['user', 'story'], name='jobs_storyr_user_id_bef341_idx'),
        ),
        migrations.AddConstraint(
            model_name='storyresonance',
            constraint=models.UniqueConstraint(condition=models.Q(('session_key__isnull', False), ('user__isnull', True)), fields=('story', 'session_key'), name='unique_session_story_resonance'),
        ),
        migrations.AddConstraint(
            model_name='storyresonance',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('story', 'user'), name='unique_user_story_resonance'),
        ),
    ]
