# Generated by Django 5.2.8 on 2025-12-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_job_source_savedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='benefits',
            field=models.TextField(blank=True, help_text='Benefits, perks, and culture notes'),
        ),
        migrations.AddField(
            model_name='job',
            name='company_description',
            field=models.TextField(blank=True, help_text='AI-extracted company bio if different from Org'),
        ),
        migrations.AddField(
            model_name='job',
            name='how_to_apply_text',
            field=models.TextField(blank=True, help_text='Specific application instructions'),
        ),
        migrations.AddField(
            model_name='job',
            name='impact',
            field=models.TextField(blank=True, help_text='Specific impact the role will drive'),
        ),
    ]
