# Generated by Django 5.2.8 on 2025-12-09 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_benefits_job_company_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sprint',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='True if payment is confirmed.'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Job is live on the site. Manual jobs are inactive until paid.'),
        ),
    ]
