# Generated by Django 5.2.8 on 2025-12-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_organization_verification_status_userprofile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('80000hours', '80,000 Hours'), ('idealist', 'Idealist'), ('reliefweb', 'ReliefWeb'), ('climatebase', 'Climatebase'), ('greenhouse', 'Greenhouse'), ('lever', 'Lever'), ('ashby', 'Ashby')], default='manual', max_length=50),
        ),
    ]
