# Generated by Django 5.2.8 on 2025-12-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_add_greenhouse_lever_ashby_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('80000hours', '80,000 Hours'), ('idealist', 'Idealist'), ('reliefweb', 'ReliefWeb'), ('climatebase', 'Climatebase'), ('greenhouse', 'Greenhouse'), ('lever', 'Lever'), ('ashby', 'Ashby'), ('probablygood', 'Probably Good')], default='manual', max_length=50),
        ),
    ]
