# Generated by Django 5.2.8 on 2026-01-04 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_add_probablygood_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro ($149/mo)'), ('growth', 'Growth ($299/mo)'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100)),
                ('invites_used_this_month', models.PositiveIntegerField(default=0)),
                ('invites_reset_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='jobs.organization')),
            ],
            options={
                'verbose_name': 'Organization Subscription',
                'verbose_name_plural': 'Organization Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='SeekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_style', models.CharField(blank=True, choices=[('builder', 'Building things (engineering, product, design)'), ('strategist', 'Moving ideas (strategy, communications, policy)'), ('operator', 'Running operations (ops, finance, HR, admin)'), ('direct', 'Direct service (program delivery, field work)'), ('researcher', 'Research & analysis')], max_length=20)),
                ('experience_level', models.CharField(blank=True, choices=[('early', 'Early career (0-2 years)'), ('mid', 'Mid-level (3-6 years)'), ('senior', 'Senior (7-12 years)'), ('leadership', 'Leadership (12+ years)'), ('career_changer', 'Career changer')], max_length=20)),
                ('skills', models.JSONField(default=list, help_text="List of skill slugs, e.g. ['python', 'data-analysis']")),
                ('remote_preference', models.CharField(blank=True, choices=[('remote', 'Fully remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site'), ('flexible', 'Flexible')], max_length=20)),
                ('location_preferences', models.JSONField(default=list, help_text="ISO country codes or regions, e.g. ['US', 'GB', 'europe']")),
                ('salary_min', models.PositiveIntegerField(blank=True, help_text='Minimum expected salary (USD)', null=True)),
                ('salary_max', models.PositiveIntegerField(blank=True, help_text='Maximum expected salary (USD)', null=True)),
                ('job_types', models.JSONField(default=list, help_text="e.g. ['full-time', 'contract', 'part-time']")),
                ('impact_statement', models.TextField(blank=True, help_text='2-3 sentences on what draws them to impact work', max_length=500)),
                ('assessment_answers', models.JSONField(default=dict, help_text="Answers to optional assessment questions, e.g. {'time_horizon': 'future', 'org_size': 'startup'}")),
                ('visibility', models.CharField(choices=[('public', 'Public - visible to all orgs'), ('matching', 'Visible to matching orgs only'), ('hidden', 'Hidden from talent search')], default='public', max_length=20)),
                ('is_actively_looking', models.BooleanField(default=True, help_text='Currently seeking opportunities')),
                ('wizard_completed', models.BooleanField(default=False)),
                ('wizard_step', models.PositiveIntegerField(default=0, help_text='Current step in onboarding wizard (0 = not started)')),
                ('profile_completeness', models.PositiveIntegerField(default=0, help_text='Profile completeness percentage 0-100')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('impact_areas', models.ManyToManyField(blank=True, related_name='interested_seekers', to='jobs.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seeker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seeker Profile',
                'verbose_name_plural': 'Seeker Profiles',
            },
        ),
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_text', models.TextField()),
                ('final_text', models.TextField(blank=True)),
                ('used_in_application', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letters', to='jobs.job')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letters', to='jobs.seekerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(db_index=True)),
                ('breakdown', models.JSONField(default=dict, help_text="{'impact': 85, 'skills': 70, 'experience': 100, 'location': 80, 'salary': 60}")),
                ('reasons', models.JSONField(default=list, help_text="['Climate focus matches', '8 of 10 required skills', ...]")),
                ('gaps', models.JSONField(default=list, help_text="['Terraform', 'AWS', ...] - skills job wants that seeker lacks")),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeker_matches', to='jobs.job')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='jobs.seekerprofile')),
            ],
            options={
                'ordering': ['-score'],
                'indexes': [models.Index(fields=['seeker', '-score'], name='jobs_jobmat_seeker__e63e2d_idx'), models.Index(fields=['job', '-score'], name='jobs_jobmat_job_id_ef12de_idx')],
                'unique_together': {('seeker', 'job')},
            },
        ),
        migrations.CreateModel(
            name='TalentInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('viewed', 'Viewed'), ('applied', 'Applied'), ('declined', 'Declined')], default='sent', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_invitations', to='jobs.job')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_invitations', to='jobs.organization')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_received', to='jobs.seekerprofile')),
            ],
            options={
                'ordering': ['-sent_at'],
                'unique_together': {('job', 'seeker')},
            },
        ),
    ]
