# Generated by Django 5.2.8 on 2026-01-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_add_impact_match_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.JSONField(blank=True, default=list, help_text='AI-extracted skill slugs from job'),
        ),
    ]
