# Generated by Django 5.2.8 on 2026-01-06 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_add_skills_to_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_uses_remaining', models.PositiveIntegerField(default=3)),
                ('total_uses', models.PositiveIntegerField(default=0)),
                ('is_subscribed', models.BooleanField(default=False)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100)),
                ('subscribed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assistant Subscription',
                'verbose_name_plural': 'Assistant Subscriptions',
            },
        ),
    ]
