# Generated by Django 5.2.8 on 2026-01-06 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_add_assistant_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_type', models.CharField(choices=[('cover_letter', 'Cover Letter'), ('interview_prep', 'Interview Prep')], default='cover_letter', max_length=20)),
                ('job_url', models.URLField(blank=True)),
                ('job_description', models.TextField(blank=True)),
                ('user_highlights', models.TextField(blank=True)),
                ('generated_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assistant Generation',
                'verbose_name_plural': 'Assistant Generations',
                'ordering': ['-created_at'],
            },
        ),
    ]
