# Generated by Django 5.2.8 on 2026-01-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_add_assistant_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_newsletter',
            field=models.BooleanField(default=True, help_text='Receive weekly job digest emails'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_newsletter_unsubscribed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
