# Generated by Django 5.2.8 on 2026-01-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_add_newsletter_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='application_url',
            field=models.TextField(help_text='URL to apply for this job'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.TextField(blank=True),
        ),
    ]
