# Generated by Django 5.2.8 on 2026-01-13 21:59

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_increase_field_lengths'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='job',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='job_search_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='job_embedding_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='seekerprofile',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='seeker_search_idx'),
        ),
        migrations.AddIndex(
            model_name='seekerprofile',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='seeker_embedding_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
