# Generated by Django 5.2.8 on 2026-01-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_add_newsletter_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='bcorp_profile_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='bcorp_score',
            field=models.PositiveIntegerField(blank=True, help_text='B Corp overall score (80-200+)', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='financials_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='founded_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='has_public_financials',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='has_public_impact_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='impact_metric_name',
            field=models.CharField(blank=True, help_text="e.g., 'Lives saved', 'Trees planted', 'Students taught'", max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='impact_metric_value',
            field=models.CharField(blank=True, help_text="e.g., '50,000+', '1.2M', '10,000/year'", max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='impact_profile_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='impact_report_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='impact_statement',
            field=models.TextField(blank=True, help_text="Brief statement about your organization's impact (2-3 sentences)"),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_80k_recommended',
            field=models.BooleanField(default=False, help_text='Listed on 80,000 Hours job board'),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_bcorp_certified',
            field=models.BooleanField(default=False, help_text='Certified B Corporation'),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_givewell_top_charity',
            field=models.BooleanField(default=False, help_text='GiveWell top or standout charity'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(blank=True, choices=[('nonprofit', 'Nonprofit / NGO'), ('social_enterprise', 'Social Enterprise'), ('bcorp', 'B Corporation'), ('government', 'Government / Public Sector'), ('foundation', 'Foundation'), ('research', 'Research Institution'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='organization',
            name='remote_culture',
            field=models.CharField(blank=True, choices=[('remote_first', 'Remote-first'), ('hybrid', 'Hybrid'), ('office_first', 'Office-first')], max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='team_size',
            field=models.CharField(blank=True, choices=[('1-10', '1-10'), ('11-50', '11-50'), ('51-200', '51-200'), ('201-500', '201-500'), ('500+', '500+')], max_length=20),
        ),
    ]
