# Generated by Django 5.2.8 on 2026-01-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_add_org_impact_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='country',
            field=models.CharField(blank=True, help_text='Normalized country name for filtering', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='education_level',
            field=models.CharField(blank=True, choices=[('high_school', 'High School'), ('associate', 'Associate'), ('bachelor', "Bachelor's"), ('master', "Master's"), ('phd', 'PhD')], help_text='Minimum education level required', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior'), ('executive', 'Executive'), ('internship', 'Internship')], help_text='Experience level required for this job', max_length=50, null=True),
        ),
    ]
