# Generated by Django 5.2.8 on 2026-01-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0029_referral_and_job_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, help_text='PDF or DOC resume (max 5 MB)', null=True, upload_to='applications/resumes/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='resume',
            field=models.FileField(blank=True, help_text='PDF or DOC resume (max 5 MB)', null=True, upload_to='seekers/resumes/%Y/%m/'),
        ),
    ]
