# Generated by Django 5.2.8 on 2026-05-03 11:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0032_organization_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionScreeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('mission_alignment', 'Mission Alignment'), ('culture_fit', 'Culture Fit'), ('skills_validation', 'Skills Validation'), ('experience', 'Experience')], default='mission_alignment', max_length=30)),
                ('question_text', models.TextField(help_text='The screening question to present to applicants')),
                ('context', models.JSONField(blank=True, default=dict, help_text='Context used to generate question (org mission, role impact, etc.)')),
                ('llm_model', models.CharField(blank=True, help_text='Which LLM generated this (e.g., deepseek-chat)', max_length=100)),
                ('llm_cost_usd', models.DecimalField(decimal_places=6, default=0, help_text='Cost to generate this question', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_questions', to='jobs.job')),
            ],
            options={
                'ordering': ['question_type', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplicationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(help_text="Applicant's written response to the question")),
                ('time_taken_seconds', models.PositiveIntegerField(blank=True, help_text='Time taken to answer in seconds', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_responses', to='jobs.application')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='jobs.missionscreeningquestion')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active - Accepting Applications'), ('review', 'Under Review'), ('closed', 'Closed')], default='draft', help_text='Current screening session status', max_length=20)),
                ('screening_questions', models.JSONField(blank=True, default=list, help_text="List of screening questions: [{'id': 'q1', 'question': '...', 'required': True}]")),
                ('skills_weight', models.PositiveIntegerField(default=40, help_text='Weight for skills alignment (0-100)')),
                ('mission_weight', models.PositiveIntegerField(default=35, help_text='Weight for mission alignment (0-100)')),
                ('culture_weight', models.PositiveIntegerField(default=25, help_text='Weight for culture fit (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screening_session', to='jobs.job')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skills_score', models.PositiveIntegerField(default=0, help_text='Skills alignment score')),
                ('mission_score', models.PositiveIntegerField(default=0, help_text='Mission alignment score')),
                ('culture_score', models.PositiveIntegerField(default=0, help_text='Culture fit score')),
                ('combined_score', models.PositiveIntegerField(default=0, help_text='Weighted combined score')),
                ('reasoning', models.TextField(blank=True, help_text='AI-generated reasoning for the scores')),
                ('has_concerns', models.BooleanField(default=False, help_text='Flag if there are significant concerns')),
                ('concerns_text', models.TextField(blank=True, help_text='Details about concerns if any')),
                ('team_recommendation', models.CharField(choices=[('strong_yes', 'Strong Yes'), ('yes', 'Yes'), ('maybe', 'Maybe'), ('no', 'No'), ('strong_no', 'Strong No'), ('pending', 'Pending Review')], default='pending', help_text='Team consensus recommendation', max_length=20)),
                ('team_consensus_score', models.FloatField(default=0.0, help_text='Average team rating (0-5)')),
                ('screening_answers', models.JSONField(blank=True, default=dict, help_text="Answers to screening questions: {'q1': 'answer text', ...}")),
                ('ranked_position', models.PositiveIntegerField(blank=True, help_text='Rank in shortlist (1-20)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scored_at', models.DateTimeField(blank=True, help_text='When AI scoring was completed', null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screening_candidate', to='jobs.application')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='jobs.screeningsession')),
            ],
            options={
                'ordering': ['-combined_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], help_text='Rating from 1 (Poor) to 5 (Excellent)')),
                ('comment', models.TextField(blank=True, help_text='Detailed feedback comment')),
                ('recommendation', models.CharField(choices=[('strong_yes', 'Strong Yes'), ('yes', 'Yes'), ('maybe', 'Maybe'), ('no', 'No'), ('strong_no', 'Strong No'), ('pending', 'Pending Review')], default='pending', help_text="Reviewer's recommendation", max_length=20)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_feedback', to='jobs.screeningcandidate')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.DecimalField(decimal_places=2, help_text='Overall mission fit score (0-100)', max_digits=5)),
                ('mission_alignment_score', models.DecimalField(decimal_places=2, default=0, help_text='How well candidate aligns with org mission (0-100)', max_digits=5)),
                ('skills_match_score', models.DecimalField(decimal_places=2, default=0, help_text='How well candidate matches required skills (0-100)', max_digits=5)),
                ('culture_fit_score', models.DecimalField(decimal_places=2, default=0, help_text='How well candidate fits team culture (0-100)', max_digits=5)),
                ('scoring_breakdown', models.JSONField(blank=True, default=dict, help_text='Detailed scoring rationale and reasoning from LLM')),
                ('recommendation', models.CharField(blank=True, choices=[('strong_yes', 'Strong Yes - Highly Recommended'), ('yes', 'Yes - Recommend'), ('maybe', 'Maybe - Review Manually'), ('no', 'No - Not Recommended')], help_text='Auto-generated hiring recommendation', max_length=20)),
                ('recommendation_reason', models.TextField(blank=True, help_text='Explanation for the recommendation')),
                ('llm_model', models.CharField(blank=True, help_text='Which LLM scored this', max_length=100)),
                ('llm_cost_usd', models.DecimalField(decimal_places=6, default=0, help_text='Cost to score this application', max_digits=10)),
                ('scored_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hire_for_mission_score', to='jobs.application')),
            ],
            options={
                'ordering': ['-overall_score'],
                'indexes': [models.Index(fields=['-overall_score'], name='jobs_applic_overall_808ae3_idx'), models.Index(fields=['application'], name='jobs_applic_applica_3cafd1_idx')],
            },
        ),
        migrations.CreateModel(
            name='HiringFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_score_helpful', models.BooleanField(blank=True, help_text='Was the AI score helpful for decision-making?', null=True)),
                ('score_accuracy', models.CharField(blank=True, choices=[('very_accurate', 'Very Accurate'), ('accurate', 'Accurate'), ('somewhat_accurate', 'Somewhat Accurate'), ('inaccurate', 'Inaccurate')], help_text='How accurate was the AI score?', max_length=20)),
                ('hiring_decision', models.CharField(blank=True, choices=[('applied', 'Applied'), ('reviewed', 'Reviewed'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejected', 'Rejected')], help_text='What was the final hiring decision?', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes from hiring team')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hiring_feedback', to='jobs.application')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hiring_feedback_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['application'], name='jobs_hiring_applica_61847b_idx'), models.Index(fields=['-submitted_at'], name='jobs_hiring_submitt_d134d4_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='missionscreeningquestion',
            index=models.Index(fields=['job', 'is_active'], name='jobs_missio_job_id_abff4f_idx'),
        ),
        migrations.AddIndex(
            model_name='missionscreeningquestion',
            index=models.Index(fields=['-created_at'], name='jobs_missio_created_d4c3a0_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplicationresponse',
            index=models.Index(fields=['application', 'question'], name='jobs_jobapp_applica_e93d41_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplicationresponse',
            unique_together={('application', 'question')},
        ),
        migrations.AddIndex(
            model_name='screeningsession',
            index=models.Index(fields=['status', '-created_at'], name='jobs_screen_status_ea8189_idx'),
        ),
        migrations.AddIndex(
            model_name='screeningsession',
            index=models.Index(fields=['job', 'status'], name='jobs_screen_job_id_11136f_idx'),
        ),
        migrations.AddIndex(
            model_name='screeningcandidate',
            index=models.Index(fields=['session', '-combined_score'], name='jobs_screen_session_e97b32_idx'),
        ),
        migrations.AddIndex(
            model_name='screeningcandidate',
            index=models.Index(fields=['session', 'team_recommendation'], name='jobs_screen_session_55a7f8_idx'),
        ),
        migrations.AddIndex(
            model_name='screeningcandidate',
            index=models.Index(fields=['has_concerns'], name='jobs_screen_has_con_80b054_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='screeningcandidate',
            unique_together={('session', 'application')},
        ),
        migrations.AddIndex(
            model_name='teamfeedback',
            index=models.Index(fields=['candidate', 'reviewer'], name='jobs_teamfe_candida_b3794c_idx'),
        ),
        migrations.AddIndex(
            model_name='teamfeedback',
            index=models.Index(fields=['candidate', 'rating'], name='jobs_teamfe_candida_debca3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teamfeedback',
            unique_together={('candidate', 'reviewer')},
        ),
    ]
