"""
Django settings for jobboard project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY", "django-insecure-=n&5^u0k_37en98tutnqe50ag^c-2(*qkjjp29wg!9!i@7(d1$"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True").lower() in ("true", "1", "yes")

ALLOWED_HOSTS = [
    h.strip()
    for h in os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if h.strip()
]

# CSRF trusted origins for production
CSRF_TRUSTED_ORIGINS = [
    f"https://{h}"
    for h in ALLOWED_HOSTS
    if h and not h.startswith("localhost") and not h.startswith("127.")
]
if DEBUG:
    CSRF_TRUSTED_ORIGINS.append("http://localhost:8000")

# Site URL for SEO (canonical URLs, sitemaps, OG tags)
SITE_URL = os.getenv("SITE_URL", "https://remoteimpact.org")
SITE_NAME = "Remote Impact"

# Trust X-Forwarded-Proto header from reverse proxy (for HTTPS detection)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django.contrib.sitemaps",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "django_extensions",
    "django_countries",
    "jobs",
    "gigs",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Serve static files in production
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "jobboard.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "jobs.context_processors.site_settings",  # SEO settings
            ],
        },
    },
]

WSGI_APPLICATION = "jobboard.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": Path(os.getenv("DATABASE_PATH", BASE_DIR / "db.sqlite3")),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"  # For collectstatic in production
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
SITE_ID = 1
LOGIN_REDIRECT_URL = "/onboarding/"
LOGOUT_REDIRECT_URL = "/"
LOGIN_URL = "/accounts/login/"

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

# External job ingestion settings
EIGHTYK_ALGOLIA_APP_ID = os.getenv("EIGHTYK_ALGOLIA_APP_ID", "W6KM1UDIB3")
EIGHTYK_ALGOLIA_API_KEY = os.getenv(
    "EIGHTYK_ALGOLIA_API_KEY", "d1d7f2c8696e7b36837d5ed337c4a319"
)
IDEALIST_ALGOLIA_APP_ID = os.getenv("IDEALIST_ALGOLIA_APP_ID", "NSV3AUESS7")
IDEALIST_ALGOLIA_API_KEY = os.getenv(
    "IDEALIST_ALGOLIA_API_KEY", "c2730ea10ab82787f2f3cc961e8c1e06"
)
RELIEFWEB_APP_NAME = os.getenv(
    "RELIEFWEB_APP_NAME", "RemoteImpactOrg-Individual-E7V8AptCBw"
)
CLIMATEBASE_ALGOLIA_APP_ID = os.getenv("CLIMATEBASE_ALGOLIA_APP_ID", "8PSNFFQTXQ")
CLIMATEBASE_ALGOLIA_API_KEY = os.getenv(
    "CLIMATEBASE_ALGOLIA_API_KEY", "d2ebe27d3cc3d35fea04da7b1b0718a8"
)

# Serper.dev API for Google Search (2,500 free searches/month)
# Get your free API key at: https://serper.dev
SERPER_API_KEY = os.getenv("SERPER_API_KEY", "")

# Google Custom Search API (100 free queries/day)
# Get your API key at: https://console.cloud.google.com/apis/credentials
# Create a Custom Search Engine at: https://cse.google.com/cse/
GOOGLE_CSE_API_KEY = os.getenv("GOOGLE_CSE_API_KEY", "AIzaSyB80R9QJjZLxw_tQqxUj82f49Rn4JQBQo")
GOOGLE_CSE_CX = os.getenv("GOOGLE_CSE_CX", "d29e1be4453804e08")

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": os.getenv("GOOGLE_CLIENT_ID", ""),
            "secret": os.getenv("GOOGLE_CLIENT_SECRET", ""),
            "key": "",
        },
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
    }
}


# LLM API Keys - Priority: DeepSeek (cheapest) > Groq (free) > Mistral
# Get DeepSeek key at: https://platform.deepseek.com/api_keys (~$0.14/1M tokens)
DEEPSEEK_API_KEY = os.getenv("DEEPSEEK_API_KEY", "")
# Get Groq key at: https://console.groq.com/keys (free tier: 14,400 req/day)
GROQ_API_KEY = os.getenv("GROQ_API_KEY", "")
# Mistral (fallback, more expensive)
MISTRAL_API_KEY = os.getenv("MISTRAL_API_KEY", "")

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")

STRIPE_PUBLISHABLE_KEY = os.getenv("STRIPE_PUBLISHABLE_KEY", "")
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY", "")

# Email settings for development
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
ACCOUNT_EMAIL_VERIFICATION = "none"
# New allauth settings (replaces deprecated ACCOUNT_EMAIL_REQUIRED, ACCOUNT_AUTHENTICATION_METHOD, ACCOUNT_USERNAME_REQUIRED)
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
