# Generated by Django 5.2.8 on 2026-04-19 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-published_at']},
        ),
        migrations.RenameIndex(
            model_name='blogpost',
            new_name='blog_blogpo_status_c0e87f_idx',
            old_name='blog_blogpo_status_idx',
        ),
        migrations.RenameIndex(
            model_name='blogpost',
            new_name='blog_blogpo_slug_361555_idx',
            old_name='blog_blogpo_slug_idx',
        ),
    ]
