"""
SEO Configuration for Programmatic Landing Pages

Defines role patterns, metadata, and content for SEO pages like:
- /remote-software-engineer-jobs/
- /remote-data-analyst-jobs/
- etc.
"""

# Role configurations for SEO pages
# Each role has: slug, display_name, search_patterns, meta info
ROLE_SEO_PAGES = [
    {
        'slug': 'remote-software-engineer-jobs',
        'role': 'Software Engineer',
        'patterns': ['software engineer', 'software developer', 'swe'],
        'h1': 'Remote Software Engineer Jobs',
        'title': 'Remote Software Engineer Jobs (2026) | {count}+ Open Roles',
        'meta_desc': 'Find {count}+ remote software engineer jobs at impact organizations. Work on climate tech, AI safety, global health & more. Updated daily.',
        'intro': 'Software engineers are building the future of impact. From climate modeling systems to AI safety tools, these roles let you write code that matters.',
        'icon': '💻',
    },
    {
        'slug': 'remote-data-scientist-jobs',
        'role': 'Data Scientist',
        'patterns': ['data scientist', 'data science'],
        'h1': 'Remote Data Scientist Jobs',
        'title': 'Remote Data Scientist Jobs (2026) | {count}+ Impact Roles',
        'meta_desc': 'Find {count}+ remote data scientist jobs at purpose-driven organizations. Apply ML and analytics to climate, health, and social impact.',
        'intro': 'Data scientists are uncovering insights that drive impact. From predicting disease outbreaks to optimizing clean energy, your models can change the world.',
        'icon': '📊',
    },
    {
        'slug': 'remote-data-analyst-jobs',
        'role': 'Data Analyst',
        'patterns': ['data analyst', 'analytics analyst', 'business analyst'],
        'h1': 'Remote Data Analyst Jobs',
        'title': 'Remote Data Analyst Jobs (2026) | {count}+ Open Positions',
        'meta_desc': 'Find {count}+ remote data analyst jobs at impact organizations. Turn data into decisions for climate, health, and social good.',
        'intro': 'Data analysts turn raw numbers into actionable insights. These roles combine analytical skills with meaningful impact.',
        'icon': '📈',
    },
    {
        'slug': 'remote-product-manager-jobs',
        'role': 'Product Manager',
        'patterns': ['product manager', 'product lead', 'product owner'],
        'h1': 'Remote Product Manager Jobs',
        'title': 'Remote Product Manager Jobs (2026) | {count}+ PM Roles',
        'meta_desc': 'Find {count}+ remote product manager jobs at impact organizations. Build products that tackle climate change, improve health, and drive social good.',
        'intro': 'Product managers shape products that millions rely on. In impact orgs, you\'ll build tools that help nonprofits scale, researchers collaborate, and communities thrive.',
        'icon': '🎯',
    },
    {
        'slug': 'remote-project-manager-jobs',
        'role': 'Project Manager',
        'patterns': ['project manager', 'project lead', 'project coordinator'],
        'h1': 'Remote Project Manager Jobs',
        'title': 'Remote Project Manager Jobs (2026) | {count}+ Roles',
        'meta_desc': 'Find {count}+ remote project manager jobs at purpose-driven organizations. Lead initiatives in climate, global health, and social impact.',
        'intro': 'Project managers keep impact initiatives on track. From coordinating global health programs to launching climate campaigns, you\'ll make things happen.',
        'icon': '📋',
    },
    {
        'slug': 'remote-program-manager-jobs',
        'role': 'Program Manager',
        'patterns': ['program manager', 'program director', 'program lead'],
        'h1': 'Remote Program Manager Jobs',
        'title': 'Remote Program Manager Jobs (2026) | {count}+ Positions',
        'meta_desc': 'Find {count}+ remote program manager jobs at impact organizations. Design and run programs that create lasting social change.',
        'intro': 'Program managers design and run initiatives that create systemic change. These roles combine strategy with execution across climate, health, and social sectors.',
        'icon': '🎪',
    },
    {
        'slug': 'remote-marketing-manager-jobs',
        'role': 'Marketing Manager',
        'patterns': ['marketing manager', 'marketing director', 'marketing lead', 'head of marketing'],
        'h1': 'Remote Marketing Manager Jobs',
        'title': 'Remote Marketing Manager Jobs (2026) | {count}+ Roles',
        'meta_desc': 'Find {count}+ remote marketing manager jobs at impact organizations. Amplify messages that matter for climate, health, and social good.',
        'intro': 'Marketing managers amplify impact. From growing awareness of climate solutions to driving donations for global health, your campaigns can move millions.',
        'icon': '📣',
    },
    {
        'slug': 'remote-operations-manager-jobs',
        'role': 'Operations Manager',
        'patterns': ['operations manager', 'operations director', 'head of operations', 'ops manager'],
        'h1': 'Remote Operations Manager Jobs',
        'title': 'Remote Operations Manager Jobs (2026) | {count}+ Positions',
        'meta_desc': 'Find {count}+ remote operations manager jobs at impact organizations. Build systems that help mission-driven teams scale.',
        'intro': 'Operations managers are the backbone of impact organizations. You\'ll build systems that help teams work effectively, scale programs, and maximize impact.',
        'icon': '⚙️',
    },
    {
        'slug': 'remote-executive-director-jobs',
        'role': 'Executive Director',
        'patterns': ['executive director', 'ed ', 'managing director'],
        'h1': 'Remote Executive Director Jobs',
        'title': 'Remote Executive Director Jobs (2026) | {count}+ Roles',
        'meta_desc': 'Find {count}+ remote executive director jobs at purpose-driven organizations. Lead teams tackling climate, health, and social challenges.',
        'intro': 'Executive directors set the vision and lead organizations to impact. These leadership roles combine strategy, fundraising, and team building.',
        'icon': '👔',
    },
    {
        'slug': 'remote-devops-engineer-jobs',
        'role': 'DevOps Engineer',
        'patterns': ['devops', 'site reliability', 'sre', 'platform engineer', 'infrastructure engineer'],
        'h1': 'Remote DevOps Engineer Jobs',
        'title': 'Remote DevOps Engineer Jobs (2026) | {count}+ Positions',
        'meta_desc': 'Find {count}+ remote DevOps engineer jobs at impact organizations. Build infrastructure that powers climate tech, AI safety, and more.',
        'intro': 'DevOps engineers build the infrastructure that powers impact. From scaling climate modeling platforms to securing AI safety systems, your work enables everything else.',
        'icon': '🔧',
    },
    {
        'slug': 'remote-policy-analyst-jobs',
        'role': 'Policy Analyst',
        'patterns': ['policy analyst', 'policy advisor', 'policy researcher', 'policy associate'],
        'h1': 'Remote Policy Analyst Jobs',
        'title': 'Remote Policy Analyst Jobs (2026) | {count}+ Positions',
        'meta_desc': 'Find {count}+ remote policy analyst jobs at think tanks and advocacy organizations. Shape climate, tech, and social policy.',
        'intro': 'Policy analysts shape the rules that govern society. From climate regulation to AI governance, your research and analysis can influence laws and regulations worldwide.',
        'icon': '🏛️',
    },
    {
        'slug': 'remote-machine-learning-engineer-jobs',
        'role': 'Machine Learning Engineer',
        'patterns': ['machine learning', 'ml engineer', 'ai engineer', 'deep learning'],
        'h1': 'Remote Machine Learning Engineer Jobs',
        'title': 'Remote Machine Learning Engineer Jobs (2026) | {count}+ Roles',
        'meta_desc': 'Find {count}+ remote ML engineer jobs at impact organizations. Build AI systems for climate, health, and AI safety.',
        'intro': 'Machine learning engineers are at the frontier of AI for good. From climate prediction models to medical diagnosis systems, your algorithms can save lives.',
        'icon': '🤖',
    },
    {
        'slug': 'remote-communications-manager-jobs',
        'role': 'Communications Manager',
        'patterns': ['communications manager', 'communications director', 'comms manager', 'head of communications'],
        'h1': 'Remote Communications Manager Jobs',
        'title': 'Remote Communications Manager Jobs (2026) | {count}+ Roles',
        'meta_desc': 'Find {count}+ remote communications manager jobs at impact organizations. Tell stories that inspire action on climate, health, and social issues.',
        'intro': 'Communications managers craft narratives that move people to action. From press releases to social campaigns, your words can shift public opinion.',
        'icon': '✍️',
    },
    {
        'slug': 'remote-research-scientist-jobs',
        'role': 'Research Scientist',
        'patterns': ['research scientist', 'researcher', 'senior researcher', 'research fellow'],
        'h1': 'Remote Research Scientist Jobs',
        'title': 'Remote Research Scientist Jobs (2026) | {count}+ Positions',
        'meta_desc': 'Find {count}+ remote research scientist jobs at impact organizations. Conduct research on climate, AI safety, global health, and more.',
        'intro': 'Research scientists push the boundaries of knowledge. In impact orgs, your discoveries can directly translate to solutions for humanity\'s biggest challenges.',
        'icon': '🔬',
    },
    {
        'slug': 'remote-finance-manager-jobs',
        'role': 'Finance Manager',
        'patterns': ['finance manager', 'finance director', 'financial manager', 'head of finance'],
        'h1': 'Remote Finance Manager Jobs',
        'title': 'Remote Finance Manager Jobs (2026) | {count}+ Positions',
        'meta_desc': 'Find {count}+ remote finance manager jobs at impact organizations. Manage finances for mission-driven teams.',
        'intro': 'Finance managers ensure impact organizations can sustain their missions. From grant management to financial planning, you\'ll steward resources for good.',
        'icon': '💰',
    },
    {
        'slug': 'remote-accounting-jobs',
        'role': 'Accounting',
        'patterns': ['accounting', 'accountant', 'controller', 'bookkeeper', 'accounts payable', 'accounts receivable'],
        'h1': 'Remote Accounting Jobs',
        'title': 'Remote Accounting Jobs (2026) | {count}+ Finance & Nonprofit Roles',
        'meta_desc': 'Find {count}+ remote accounting jobs at nonprofits, foundations, climate organizations, and mission-driven teams. Updated daily.',
        'intro': 'Remote accounting jobs keep mission-driven organizations financially healthy. Browse roles in nonprofit accounting, grants finance, bookkeeping, and controller work.',
        'icon': '💰',
    },
    {
        'slug': 'remote-hr-jobs',
        'role': 'Human Resources',
        'patterns': ['human resources', 'hr manager', 'hr generalist', 'hr coordinator', 'people operations', 'people ops', 'people partner'],
        'h1': 'Remote HR Jobs',
        'title': 'Remote HR Jobs (2026) | {count}+ People & Talent Roles',
        'meta_desc': 'Find {count}+ remote HR jobs at impact organizations. Browse people operations, HR generalist, recruiting, and talent roles.',
        'intro': 'Remote HR teams help purpose-driven organizations hire, support, and retain great people. Find people operations and human resources roles with real impact.',
        'icon': '🤝',
    },
    {
        'slug': 'remote-education-jobs',
        'role': 'Education',
        'patterns': ['education', 'teacher', 'teaching', 'curriculum', 'learning', 'instructional designer', 'student'],
        'h1': 'Remote Education Jobs',
        'title': 'Remote Education Jobs (2026) | {count}+ Learning & Curriculum Roles',
        'meta_desc': 'Find {count}+ remote education jobs in curriculum, learning design, teaching, student support, and education nonprofits.',
        'intro': 'Remote education jobs let you improve learning outcomes from anywhere. Browse curriculum, program, student support, and learning design roles.',
        'icon': '📚',
    },
    {
        'slug': 'remote-fundraising-jobs',
        'role': 'Fundraising',
        'patterns': ['fundraising', 'fundraiser', 'development officer', 'development manager', 'major gifts', 'grant writer', 'philanthropy'],
        'h1': 'Remote Fundraising Jobs',
        'title': 'Remote Fundraising Jobs (2026) | {count}+ Development Roles',
        'meta_desc': 'Find {count}+ remote fundraising jobs at nonprofits, foundations, and charities. Development, grants, donor relations, and major gifts roles.',
        'intro': 'Remote fundraising roles help mission-driven organizations sustain and grow their work. Find development, grants, donor relations, and philanthropy jobs.',
        'icon': '🌱',
    },
    {
        'slug': 'remote-government-affairs-jobs',
        'role': 'Government Affairs',
        'patterns': ['government affairs', 'government relations', 'public affairs', 'policy manager', 'advocacy manager'],
        'h1': 'Remote Government Affairs Jobs',
        'title': 'Remote Government Affairs Jobs (2026) | {count}+ Policy Roles',
        'meta_desc': 'Find {count}+ remote government affairs jobs in public policy, advocacy, government relations, and mission-driven public affairs.',
        'intro': 'Remote government affairs roles shape policy from anywhere. Browse advocacy, public affairs, government relations, and policy roles at impact organizations.',
        'icon': '🏛️',
    },
    {
        'slug': 'remote-executive-assistant-jobs',
        'role': 'Executive Assistant',
        'patterns': ['executive assistant', 'administrative assistant', 'admin assistant', 'chief of staff', 'operations assistant'],
        'h1': 'Remote Executive Assistant Jobs',
        'title': 'Remote Executive Assistant Jobs (2026) | {count}+ Admin Roles',
        'meta_desc': 'Find {count}+ remote executive assistant jobs at nonprofits, foundations, climate teams, and mission-driven organizations.',
        'intro': 'Remote executive assistant roles keep impact leaders focused and effective. Browse administrative, operations, and chief-of-staff-adjacent roles.',
        'icon': '📋',
    },
    {
        'slug': 'remote-community-engagement-jobs',
        'role': 'Community Engagement',
        'patterns': ['community engagement', 'community manager', 'community organizer', 'community coordinator', 'outreach'],
        'h1': 'Remote Community Engagement Jobs',
        'title': 'Remote Community Engagement Jobs (2026) | {count}+ Outreach Roles',
        'meta_desc': 'Find {count}+ remote community engagement jobs in outreach, organizing, advocacy, and mission-driven community programs.',
        'intro': 'Remote community engagement jobs connect people to causes, services, and movements. Browse outreach, organizing, and program roles.',
        'icon': '🌍',
    },
    {
        'slug': 'remote-sustainability-jobs',
        'role': 'Sustainability',
        'patterns': ['sustainability', 'sustainable', 'environmental', 'climate', 'carbon', 'renewable energy'],
        'h1': 'Remote Sustainability Jobs',
        'title': 'Remote Sustainability Jobs (2026) | {count}+ Climate & ESG Roles',
        'meta_desc': 'Find {count}+ remote sustainability jobs in climate, ESG, renewable energy, carbon, conservation, and environmental impact.',
        'intro': 'Remote sustainability jobs span climate strategy, ESG, carbon, clean energy, and environmental programs. Find work that supports a livable future.',
        'icon': '🌿',
    },
    {
        'slug': 'remote-recruiter-jobs',
        'role': 'Recruiter',
        'patterns': ['recruiter', 'talent acquisition', 'talent partner', 'hiring manager'],
        'h1': 'Remote Recruiter Jobs',
        'title': 'Remote Recruiter Jobs (2026) | {count}+ Positions',
        'meta_desc': 'Find {count}+ remote recruiter jobs at impact organizations. Build teams tackling climate, health, and social challenges.',
        'intro': 'Recruiters build the teams that create impact. You\'ll help mission-driven organizations find the talent they need to change the world.',
        'icon': '🤝',
    },
    {
        'slug': 'remote-account-manager-jobs',
        'role': 'Account Manager',
        'patterns': ['account manager', 'client manager', 'customer success', 'client success'],
        'h1': 'Remote Account Manager Jobs',
        'title': 'Remote Account Manager Jobs (2026) | {count}+ Roles',
        'meta_desc': 'Find {count}+ remote account manager jobs at impact organizations. Build relationships that drive mission success.',
        'intro': 'Account managers nurture relationships that sustain impact. From managing foundation partnerships to supporting nonprofit clients, your relationship skills matter.',
        'icon': '🤲',
    },
    {
        'slug': 'remote-frontend-developer-jobs',
        'role': 'Frontend Developer',
        'patterns': ['frontend developer', 'front-end developer', 'frontend engineer', 'react developer', 'vue developer'],
        'h1': 'Remote Frontend Developer Jobs',
        'title': 'Remote Frontend Developer Jobs (2026) | {count}+ Positions',
        'meta_desc': 'Find {count}+ remote frontend developer jobs at impact organizations. Build interfaces that help people engage with climate, health, and social causes.',
        'intro': 'Frontend developers create the experiences people interact with. In impact orgs, you\'ll build dashboards, donation flows, and tools that make engagement seamless.',
        'icon': '🖥️',
    },
    {
        'slug': 'remote-backend-developer-jobs',
        'role': 'Backend Developer',
        'patterns': ['backend developer', 'back-end developer', 'backend engineer', 'server developer'],
        'h1': 'Remote Backend Developer Jobs',
        'title': 'Remote Backend Developer Jobs (2026) | {count}+ Positions',
        'meta_desc': 'Find {count}+ remote backend developer jobs at impact organizations. Build systems powering climate tech, health platforms, and social tools.',
        'intro': 'Backend developers build the systems that power impact. From APIs serving climate data to databases tracking global health, your code runs the show.',
        'icon': '⚡',
    },
    {
        'slug': 'remote-ux-designer-jobs',
        'role': 'UX Designer',
        'patterns': ['ux designer', 'user experience', 'product designer', 'ux/ui'],
        'h1': 'Remote UX Designer Jobs',
        'title': 'Remote UX Designer Jobs (2026) | {count}+ Positions',
        'meta_desc': 'Find {count}+ remote UX designer jobs at impact organizations. Design experiences that help people engage with meaningful causes.',
        'intro': 'UX designers shape how people experience impact. From designing donation flows to creating research tools, your designs make complex things simple.',
        'icon': '🎨',
    },
    {
        'slug': 'remote-intern-jobs',
        'role': 'Intern',
        'patterns': ['intern', 'internship'],
        'h1': 'Remote Internship Jobs',
        'title': 'Remote Internship Jobs (2026) | {count}+ Intern Positions',
        'meta_desc': 'Find {count}+ remote internship opportunities at impact organizations. Start your career in climate, AI safety, global health, and social impact.',
        'intro': 'Remote internships let you build experience while contributing to causes you care about. These entry points can launch careers in impact.',
        'icon': '🎓',
    },
    {
        'slug': 'remote-fellow-jobs',
        'role': 'Fellow',
        'patterns': ['fellow', 'fellowship'],
        'h1': 'Remote Fellowship Jobs',
        'title': 'Remote Fellowship Jobs (2026) | {count}+ Fellowship Opportunities',
        'meta_desc': 'Find {count}+ remote fellowship opportunities at impact organizations. Paid fellowships in climate, policy, AI safety, and more.',
        'intro': 'Fellowships offer structured learning with real impact. From policy fellowships to research positions, these programs accelerate careers in social good.',
        'icon': '📚',
    },
]

# Create a lookup dict for quick access
ROLE_SEO_LOOKUP = {page['slug']: page for page in ROLE_SEO_PAGES}

def get_role_page_config(slug):
    """Get configuration for a role-based SEO page."""
    return ROLE_SEO_LOOKUP.get(slug)

def get_all_role_slugs():
    """Get list of all role page slugs."""
    return [page['slug'] for page in ROLE_SEO_PAGES]


# =============================================================================
# KEYWORD SEO PAGES
# Target long-tail keywords from keyword planner research
# =============================================================================

KEYWORD_SEO_PAGES = [
    # Exact GSC opportunity keywords
    {
        'slug': 'remote-social-impact-jobs',
        'keyword': 'remote social impact jobs',
        'h1': 'Remote Social Impact Jobs',
        'title': 'Remote Social Impact Jobs (2026) | {count}+ Purpose-Driven Roles',
        'meta_desc': 'Find {count}+ remote social impact jobs at nonprofits, NGOs, climate organizations, health teams, and mission-driven companies. Updated daily.',
        'intro': 'Remote social impact jobs let you build a meaningful career without giving up location flexibility. Browse roles across nonprofits, climate, global health, education, advocacy, and social good.',
        'icon': '🌍',
        'filter_type': 'all',
        'difficulty': 42,
        'search_volume': 'medium',
    },
    {
        'slug': 'impact-jobs-remote',
        'keyword': 'impact jobs remote',
        'h1': 'Impact Jobs Remote',
        'title': 'Impact Jobs Remote (2026) | {count}+ Remote Impact Roles',
        'meta_desc': 'Browse {count}+ impact jobs remote-friendly and updated daily. Find purpose-driven roles in climate, AI safety, global health, nonprofits, and social good.',
        'intro': 'Looking for impact jobs remote teams are hiring for now? These roles are built around meaningful work, flexible locations, and organizations solving real-world problems.',
        'icon': '🎯',
        'filter_type': 'all',
        'difficulty': 44,
        'search_volume': 'medium',
    },
    {
        'slug': 'remote-climate-jobs',
        'keyword': 'remote climate jobs',
        'h1': 'Remote Climate Jobs',
        'title': 'Remote Climate Jobs (2026) | {count}+ Climate & Sustainability Roles',
        'meta_desc': 'Find {count}+ remote climate jobs in climate tech, sustainability, clean energy, conservation, carbon removal, and environmental policy.',
        'intro': 'Remote climate jobs span software, operations, policy, research, fundraising, and communications. Find mission-driven work helping climate organizations scale their impact.',
        'icon': '🌱',
        'filter_type': 'category',
        'category_slug': 'climate-environment',
        'patterns': ['climate', 'sustainability', 'environment', 'renewable', 'clean energy', 'carbon', 'conservation'],
        'difficulty': 38,
        'search_volume': 'medium',
    },
    {
        'slug': 'remote-part-time-jobs',
        'keyword': 'remote part time jobs',
        'h1': 'Remote Part-Time Jobs',
        'title': 'Remote Part-Time Jobs (2026) | {count}+ Flexible Impact Roles',
        'meta_desc': 'Find {count}+ remote part-time jobs at nonprofits, climate organizations, health teams, and mission-driven companies.',
        'intro': 'Remote part-time jobs can still be meaningful. Browse flexible roles at purpose-driven organizations hiring for part-time remote work.',
        'icon': '⏱️',
        'filter_type': 'job_type',
        'job_type': 'part-time',
        'difficulty': 45,
        'search_volume': 'high',
    },
    {
        'slug': 'remote-foundation-jobs',
        'keyword': 'remote foundation jobs',
        'h1': 'Remote Foundation Jobs',
        'title': 'Remote Foundation Jobs (2026) | {count}+ Philanthropy Roles',
        'meta_desc': 'Find {count}+ remote foundation jobs in philanthropy, grants, program management, operations, and social impact.',
        'intro': 'Remote foundation jobs help direct funding, strategy, and operations toward high-impact work. Browse philanthropy and grantmaking roles.',
        'icon': '🏛️',
        'filter_type': 'keyword',
        'patterns': ['foundation', 'philanthropy', 'grantmaking', 'grants', 'program officer'],
        'difficulty': 34,
        'search_volume': 'medium',
    },
    {
        'slug': 'remote-conservation-jobs',
        'keyword': 'remote conservation jobs',
        'h1': 'Remote Conservation Jobs',
        'title': 'Remote Conservation Jobs (2026) | {count}+ Environmental Roles',
        'meta_desc': 'Find {count}+ remote conservation jobs in environmental protection, biodiversity, climate, forestry, and land stewardship.',
        'intro': 'Remote conservation jobs support environmental protection, biodiversity, forestry, and climate work from distributed teams.',
        'icon': '🌲',
        'filter_type': 'keyword',
        'patterns': ['conservation', 'biodiversity', 'forestry', 'wildlife', 'environment'],
        'difficulty': 33,
        'search_volume': 'medium',
    },
    # High volume keywords
    {
        'slug': 'remote-jobs-with-purpose',
        'keyword': 'remote jobs with purpose',
        'h1': 'Remote Jobs With Purpose',
        'title': 'Remote Jobs With Purpose (2026) | {count}+ Meaningful Careers',
        'meta_desc': 'Find {count}+ remote jobs with purpose at organizations making real impact. Climate, health, education & social good roles. Updated daily.',
        'intro': 'Looking for remote work that actually matters? These aren\'t just jobs—they\'re opportunities to contribute to causes you believe in while working from anywhere.',
        'icon': '🎯',
        'filter_type': 'all',  # All jobs on platform are purpose-driven
        'difficulty': 47,
        'search_volume': 'high',
    },
    {
        'slug': 'work-from-home-impact-jobs',
        'keyword': 'work from home impact jobs',
        'h1': 'Work From Home Impact Jobs',
        'title': 'Work From Home Impact Jobs (2026) | {count}+ Remote Positions',
        'meta_desc': 'Discover {count}+ work from home impact jobs. Join organizations tackling climate change, global health, poverty & more—all remotely.',
        'intro': 'Work from home doesn\'t mean compromising on impact. These remote positions let you make a real difference from your home office.',
        'icon': '🏠',
        'filter_type': 'all',
        'difficulty': 48,
        'search_volume': 'high',
    },
    {
        'slug': 'remote-jobs-that-help-others',
        'keyword': 'remote jobs that help others',
        'h1': 'Remote Jobs That Help Others',
        'title': 'Remote Jobs That Help Others (2026) | {count}+ Helping Careers',
        'meta_desc': 'Find {count}+ remote jobs that help others. Work for nonprofits, NGOs & social enterprises making a difference—from anywhere.',
        'intro': 'Want a career centered on helping others? These remote positions connect you with organizations dedicated to improving lives around the world.',
        'icon': '🤝',
        'filter_type': 'all',
        'difficulty': 49,
        'search_volume': 'high',
    },
    {
        'slug': 'work-from-anywhere-impact-jobs',
        'keyword': 'work from anywhere impact jobs',
        'h1': 'Work From Anywhere Impact Jobs',
        'title': 'Work From Anywhere Impact Jobs (2026) | {count}+ Global Roles',
        'meta_desc': 'Find {count}+ work from anywhere impact jobs. Location-independent roles at climate, health & social impact organizations.',
        'intro': 'True location independence meets meaningful work. These global remote positions let you make an impact from anywhere in the world.',
        'icon': '🌍',
        'filter_type': 'all',
        'difficulty': 50,
        'search_volume': 'high',
    },
    # Medium volume - Nonprofit focused
    {
        'slug': 'remote-nonprofit-jobs',
        'keyword': 'remote jobs for nonprofit organizations',
        'h1': 'Remote Nonprofit Jobs',
        'title': 'Remote Nonprofit Jobs (2026) | {count}+ NGO Positions',
        'meta_desc': 'Find {count}+ remote nonprofit jobs at leading NGOs & charities. Program management, fundraising, advocacy & more.',
        'intro': 'Nonprofits are embracing remote work. Find your next role at organizations driving change in education, health, environment, and social justice.',
        'icon': '💚',
        'filter_type': 'nonprofit',
        'patterns': ['nonprofit', 'non-profit', 'ngo', 'charity', 'foundation'],
        'difficulty': 53,
        'search_volume': 'medium',
    },
    {
        'slug': 'remote-positions-in-nonprofits',
        'keyword': 'remote positions in nonprofits',
        'h1': 'Remote Positions in Nonprofits',
        'title': 'Remote Nonprofit Positions (2026) | {count}+ Available Roles',
        'meta_desc': 'Browse {count}+ remote positions in nonprofits. Find meaningful work at mission-driven organizations hiring remotely.',
        'intro': 'The nonprofit sector offers diverse remote opportunities—from entry-level coordinators to executive directors. Find your fit in the social sector.',
        'icon': '🌱',
        'filter_type': 'nonprofit',
        'patterns': ['nonprofit', 'non-profit', 'ngo', 'charity', 'foundation'],
        'difficulty': 45,
        'search_volume': 'medium',
    },
    # Humanitarian focus
    {
        'slug': 'remote-humanitarian-jobs',
        'keyword': 'remote humanitarian jobs',
        'h1': 'Remote Humanitarian Jobs',
        'title': 'Remote Humanitarian Jobs (2026) | {count}+ Aid & Relief Roles',
        'meta_desc': 'Find {count}+ remote humanitarian jobs in disaster relief, refugee support & international development. Work with top aid organizations.',
        'intro': 'Humanitarian work has gone remote. Support crisis response, refugee assistance, and development programs from anywhere in the world.',
        'icon': '🚑',
        'filter_type': 'keyword',
        'patterns': ['humanitarian', 'relief', 'refugee', 'crisis', 'emergency', 'disaster', 'aid worker', 'development'],
        'difficulty': 46,
        'search_volume': 'medium',
    },
    # Social impact
    {
        'slug': 'social-impact-remote-careers',
        'keyword': 'social impact remote careers',
        'h1': 'Social Impact Remote Careers',
        'title': 'Social Impact Remote Careers (2026) | {count}+ Opportunities',
        'meta_desc': 'Launch your social impact remote career. {count}+ positions at organizations tackling inequality, justice & community development.',
        'intro': 'Build a career in social impact without geographic constraints. These remote roles span advocacy, community development, and systemic change.',
        'icon': '✊',
        'filter_type': 'keyword',
        'patterns': ['social impact', 'social change', 'social justice', 'community', 'equity', 'advocacy'],
        'difficulty': 43,
        'search_volume': 'medium',
    },
    {
        'slug': 'remote-jobs-for-social-impact',
        'keyword': 'remote jobs for social impact',
        'h1': 'Remote Jobs for Social Impact',
        'title': 'Remote Jobs for Social Impact (2026) | {count}+ Positions',
        'meta_desc': 'Find {count}+ remote jobs for social impact. Join organizations working on poverty, education, health equity & more.',
        'intro': 'Social impact isn\'t limited by location. These remote positions connect you with organizations creating systemic change globally.',
        'icon': '🌟',
        'filter_type': 'keyword',
        'patterns': ['social impact', 'social good', 'social change', 'community', 'poverty', 'education'],
        'difficulty': 40,
        'search_volume': 'medium',
    },
    # Environmental focus
    {
        'slug': 'remote-jobs-for-environmental-impact',
        'keyword': 'remote jobs for environmental impact',
        'h1': 'Remote Environmental Impact Jobs',
        'title': 'Remote Environmental Impact Jobs (2026) | {count}+ Green Careers',
        'meta_desc': 'Find {count}+ remote environmental impact jobs. Climate tech, conservation, sustainability & clean energy roles.',
        'intro': 'Fight climate change from your home office. These remote positions span climate tech, conservation, renewable energy, and sustainability.',
        'icon': '🌿',
        'filter_type': 'keyword',
        'patterns': ['climate', 'environment', 'sustainability', 'conservation', 'renewable', 'clean energy', 'green', 'carbon'],
        'difficulty': 38,
        'search_volume': 'medium',
    },
    # Community development
    {
        'slug': 'remote-community-development-jobs',
        'keyword': 'remote community development jobs',
        'h1': 'Remote Community Development Jobs',
        'title': 'Remote Community Development Jobs (2026) | {count}+ Positions',
        'meta_desc': 'Find {count}+ remote community development jobs. Build stronger communities through organizing, advocacy & social programs.',
        'intro': 'Community development goes beyond geography. Support community organizing, local programs, and grassroots initiatives from anywhere.',
        'icon': '🏘️',
        'filter_type': 'keyword',
        'patterns': ['community', 'organizing', 'grassroots', 'local', 'neighborhood', 'civic'],
        'difficulty': 29,
        'search_volume': 'low',
    },
    # Social enterprise
    {
        'slug': 'remote-social-enterprise-jobs',
        'keyword': 'remote positions in social enterprises',
        'h1': 'Remote Social Enterprise Jobs',
        'title': 'Remote Social Enterprise Jobs (2026) | {count}+ Startup Roles',
        'meta_desc': 'Find {count}+ remote social enterprise jobs. Join mission-driven startups & B Corps solving social problems through business.',
        'intro': 'Social enterprises blend purpose with profit. Find remote roles at impact startups, B Corps, and mission-driven companies.',
        'icon': '🚀',
        'filter_type': 'keyword',
        'patterns': ['social enterprise', 'b corp', 'impact startup', 'mission-driven', 'purpose-driven'],
        'difficulty': 32,
        'search_volume': 'low',
    },
    # Charity
    {
        'slug': 'remote-charity-jobs',
        'keyword': 'remote roles in charity organizations',
        'h1': 'Remote Charity Jobs',
        'title': 'Remote Charity Jobs (2026) | {count}+ Charitable Organization Roles',
        'meta_desc': 'Find {count}+ remote charity jobs. Fundraising, program management & operations roles at charitable organizations worldwide.',
        'intro': 'Charities worldwide are hiring remotely. From fundraising to program delivery, find your role in the charitable sector.',
        'icon': '❤️',
        'filter_type': 'nonprofit',
        'patterns': ['charity', 'charitable', 'donation', 'giving', 'philanthropy'],
        'difficulty': 30,
        'search_volume': 'low',
    },
    # Online jobs for social good
    {
        'slug': 'online-jobs-for-social-good',
        'keyword': 'online jobs for social good',
        'h1': 'Online Jobs for Social Good',
        'title': 'Online Jobs for Social Good (2026) | {count}+ Digital Impact Roles',
        'meta_desc': 'Find {count}+ online jobs for social good. Digital-first roles at organizations making a positive difference in the world.',
        'intro': 'Digital skills meet social purpose. These online positions let you contribute to causes you care about through remote, digital work.',
        'icon': '💻',
        'filter_type': 'all',
        'difficulty': 35,
        'search_volume': 'medium',
    },
    # Jobs that make a difference
    {
        'slug': 'jobs-that-make-a-difference-remote',
        'keyword': 'jobs that make a difference remote',
        'h1': 'Remote Jobs That Make a Difference',
        'title': 'Remote Jobs That Make a Difference (2026) | {count}+ Meaningful Roles',
        'meta_desc': 'Find {count}+ remote jobs that make a difference. Work for organizations solving real problems in climate, health & social justice.',
        'intro': 'Not all jobs are created equal. These remote positions offer the chance to make a genuine difference in the world.',
        'icon': '💫',
        'filter_type': 'all',
        'difficulty': 39,
        'search_volume': 'medium',
    },
]

# Create lookup dict for keyword pages
KEYWORD_SEO_LOOKUP = {page['slug']: page for page in KEYWORD_SEO_PAGES}

def get_keyword_page_config(slug):
    """Get configuration for a keyword-based SEO page."""
    return KEYWORD_SEO_LOOKUP.get(slug)

def get_all_keyword_slugs():
    """Get list of all keyword page slugs."""
    return [page['slug'] for page in KEYWORD_SEO_PAGES]
