# Generated by Django 5.2.8

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0010_organization_verification_status_userprofile_country"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GigCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "is_field",
                    models.BooleanField(
                        default=False,
                        help_text="True for in-country / field categories",
                    ),
                ),
                (
                    "rubric_templates",
                    models.JSONField(
                        blank=True, default=list, help_text="List of rubric template dicts"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Gig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                (
                    "remote_policy",
                    models.CharField(
                        choices=[
                            ("anywhere", "Remote anywhere"),
                            ("timezone", "Timezone restricted"),
                            ("country", "Country restricted"),
                        ],
                        default="anywhere",
                        max_length=20,
                    ),
                ),
                (
                    "eligible_countries",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of ISO country codes",
                    ),
                ),
                ("timezone_overlap", models.CharField(blank=True, max_length=200)),
                (
                    "budget_fixed_cents",
                    models.PositiveIntegerField(
                        help_text="Fixed fee in cents (>= $50)",
                        validators=[django.core.validators.MinValueValidator(5000)],
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "trial_fee_cents",
                    models.PositiveIntegerField(
                        help_text="Trial fee in cents (>= $50)",
                        validators=[django.core.validators.MinValueValidator(5000)],
                    ),
                ),
                (
                    "trial_hours_cap",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0.25)],
                    ),
                ),
                ("trial_due_days", models.PositiveIntegerField(default=3)),
                ("deliverables", models.JSONField(blank=True, default=list)),
                ("definition_of_done", models.TextField()),
                ("brief_redacted", models.TextField()),
                ("brief_full", models.TextField()),
                (
                    "nda_required",
                    models.BooleanField(
                        default=False, help_text="Require NDA before full brief"
                    ),
                ),
                (
                    "requires_field_verification",
                    models.BooleanField(
                        default=False,
                        help_text="True for field gigs that need extra verification",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending review"),
                            ("live", "Live"),
                            ("paused", "Paused"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gigs",
                        to="gigs.gigcategory",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gigs",
                        to="jobs.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("summary", models.TextField(blank=True)),
                ("links", models.JSONField(blank=True, default=list)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="portfolio/files/"
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("application_only", "Application only"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "seeker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RubricCriterion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("weight", models.PositiveIntegerField(default=1)),
                ("max_score", models.PositiveIntegerField(default=5)),
                (
                    "gig",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rubric",
                        to="gigs.gig",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="GigApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("motivation", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("shortlisted", "Shortlisted"),
                            ("trial_offered", "Trial offered"),
                            ("trial_funded", "Trial funded"),
                            ("trial_submitted", "Trial submitted"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gig",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="gigs.gig",
                    ),
                ),
                (
                    "seeker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gig_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "selected_portfolio_items",
                    models.ManyToManyField(
                        blank=True, related_name="applications", to="gigs.portfolioitem"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("gig", "seeker")},
            },
        ),
        migrations.CreateModel(
            name="Trial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fee_cents",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(5000)]
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                (
                    "funding_status",
                    models.CharField(
                        choices=[
                            ("not_funded", "Not funded"),
                            ("funded", "Funded"),
                            ("released", "Released"),
                            ("refunded", "Refunded"),
                        ],
                        default="not_funded",
                        max_length=20,
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True,
                        help_text="Off-platform payment receipt/reference",
                        max_length=255,
                    ),
                ),
                (
                    "payment_intent_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe payment intent for future integration",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trial",
                        to="gigs.gigapplication",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artifact_links", models.JSONField(blank=True, default=list)),
                (
                    "artifact_files",
                    models.FileField(
                        blank=True, null=True, upload_to="gigs/submissions/"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="gigs.gigapplication",
                    ),
                ),
                (
                    "trial",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission",
                        to="gigs.trial",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scores", models.JSONField(blank=True, default=dict)),
                ("overall_comment", models.TextField(blank=True)),
                (
                    "decision",
                    models.CharField(
                        choices=[("pass", "Pass"), ("fail", "Fail")], max_length=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="gigs.gigapplication",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gig_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FieldVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=2)),
                ("phone_verified", models.BooleanField(default=False)),
                ("id_doc_verified", models.BooleanField(default=False)),
                (
                    "verification_level",
                    models.CharField(
                        choices=[("basic", "Basic"), ("enhanced", "Enhanced")],
                        default="basic",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "seeker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FieldEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "geo_photos",
                    models.FileField(
                        blank=True, null=True, upload_to="gigs/field_evidence/photos/"
                    ),
                ),
                (
                    "receipts",
                    models.FileField(
                        blank=True, null=True, upload_to="gigs/field_evidence/receipts/"
                    ),
                ),
                (
                    "call_logs",
                    models.FileField(
                        blank=True, null=True, upload_to="gigs/field_evidence/call_logs/"
                    ),
                ),
                ("witness_contact", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_evidence",
                        to="gigs.submission",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="gig",
            index=models.Index(
                fields=["status", "-published_at"], name="gigs_gig_status_12d6f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gig",
            index=models.Index(
                fields=["remote_policy", "status"], name="gigs_gig_remote__d53a90_idx"
            ),
        ),
    ]
