# Generated by Django 5.2.8 on 2025-12-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GigInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True, help_text='Optional message from the user')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='gig',
            new_name='gigs_gig_status_2a7e08_idx',
            old_name='gigs_gig_status_12d6f8_idx',
        ),
        migrations.RenameIndex(
            model_name='gig',
            new_name='gigs_gig_remote__fe9d7d_idx',
            old_name='gigs_gig_remote__d53a90_idx',
        ),
    ]
